name: CI
on: [push, pull_request]
env:
  FORCE_COLOR: "1"
  PRE_COMMIT_COLOR: "always"
  # See https://github.com/theacodes/nox/issues/545
  # and https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763
  SETUPTOOLS_USE_DISTUTILS: "stdlib"
jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install
        run: |
          pip install invoke towncrier sphinxcontrib-autoprogram
          pip install .
      - name: Docs
        run: inv docs
